sudo: required
services:
    - docker
    
before_install:
    - docker build -t jplata/docker-react-repo -f Dockerfile.dev .
    
script:
    - docker run jplata/docker-react-repo npm run test -- --coverage
